# Jekyll Configuration
title:
  en: Sudan Historical Photography Archive
  ar: أرشيف الصور التاريخية السودانية

description:
  en: A digital archive of photography of Sudan, run by the history department of Khartoum University.
  ar: ارشيف الصور التاريخي في قسم التاريخ جامعة الخرطوم

index:
  en: "/"
  ar: /ar

url: # "http://sudanphoto.uofk.edu" # the base hostname & protocol for your site
baseurl: "/sudanphoto" # the subpath of your site, e.g. /blog

email: sudanphoto@uofk.edu

# Build settings
markdown: kramdown
theme: minima
