# Jekyll Configuration
title:
  en: Sudan Historical Photography Archive
  ar: أرشيف الصور التاريخية السودانية

description:
  en: A digital archive of photography of Sudan, run by the history department of Khartoum University.
  ar: ارشيف الصور التاريخي في قسم التاريخ جامعة الخرطوم

index:
  en: /
  ar: /ar/index.html

url: "" # "http://sudanphoto.uofk.edu" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
gh-baseurl: "/sudanphoto"

exclude: [ Gemfile*, vendor, Rakefile, README.md, wax_tasks ]

email: sudanphoto@uofk.edu

# Build settings
permalink: html
markdown: kramdown
theme: minima

collections:
  photos-ar:
    source: photos-ar.csv
    directory: photopages/ar
    layout: photo-page
  photos-en:
    source: photos-en.csv
    directory: photopages/en
    layout: photo-page

lunr:
  content: false
  meta:
    - dir: "photopages/en"
      fields:
        - pid
        - title
        - rights
        - description
        - collection
        - _date
        - on_website
    - dir: "photopages/ar"
      fields:
        - pid
        - title
        - rights
        - description
        - collection
        - _date
        - on_website
